version: "3.3"
services:
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    restart: unless-stopped
    volumes:
      - "./certs:/etc/letsencrypt"
      - "./webroot:/var/www/certbot"
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d ${DOMAIN} --force-renewal
    depends_on:
      - nginx-challenge

  nginx-challenge:
    image: nginx:alpine
    container_name: nginx-challenge
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "./webroot:/var/www/certbot"
      - "./nginx-challenge.conf:/etc/nginx/conf.d/default.conf"

  haproxy:
    image: eeacms/haproxy
    container_name: haproxy
    restart: unless-stopped
    environment:
      - DNS_ENABLED=true
      - LOG_LEVEL=info
      - HTTP_BASIC_AUTH_USER=${LOGINNAME}
      - HTTP_BASIC_AUTH_PASSWORD=${PASSWORD}
    links:
      - glances
      - dozzle
      - netdata
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
      - "./certs:/certs:ro"
    ports:
      - "443:443"
      - "9997:9997"
      - "9998:9998"
      - "9999:9999"
      - "10000:10000"
    depends_on:
      - certbot

  glances:
    image: nicolargo/glances:dev
    container_name: glances
    restart: unless-stopped
    environment:
      - GLANCES_OPT=-w
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    pid: host
    expose:
      - "61208"
      - "61209"

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080"
      
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: your server # set to fqdn of host.
    expose:
      - "19999"
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro

  webdav:
    image: bytemark/webdav
    container_name: webdav
    restart: unless-stopped
    expose:
      - "80"
    environment:
      AUTH_TYPE: Digest
      USERNAME: ${LOGINNAME}
      PASSWORD: ${PASSWORD}
    volumes:
      - "./dav:/var/lib/dav"

  # Certbot renewal service
  certbot-renewal:
    image: certbot/certbot:latest
    container_name: certbot-renewal
    restart: unless-stopped
    volumes:
      - "./certs:/etc/letsencrypt"
      - "./webroot:/var/www/certbot"
    command: sh -c "trap exit TERM; while :; do certbot renew --webroot --webroot-path=/var/www/certbot; sleep 12h & wait $${!}; done;"
    depends_on:
      - nginx-challenge

volumes:
  netdataconfig:
  netdatalib:
  netdatacache: